### ISSUE TITLE
"Save" and "Save As" don't *appear* to allow overwriting of existing files

### ISSUE THREAD

**Issue by mcdc64** [maximised/notes-app#7]
If you type a filename into the box in "Save" or "Save As" that already exists in the folder, another dialog box pops up with a warning (making it appear as though the file wasn't saved). However, opening the file again shows that it actually was saved. So this bug is more aesthetic than anything else.

**Comment by Conrad-Crowley** [comment]
What does the warning message say?

**Comment by mcdc64** [comment]
It has a red triangle and a path (presumably leading to the existing file) that cuts off at the end so I can't see the whole thing.
Here's a screenshot: https://i.imgur.com/LZzxeYw.png

**Comment by mcdc64** [comment]
The update that fixes the Cancelling crash problem also appears to fix this one. Now when I try and overwrite something it just asks "Are you sure you want to overwrite it?" So it looks OK now.
